:mage: Render new nodetypes for Sphinx autodoc
jupyter-book/myst-theme pull request #431
Opened 2024-07-20 14:21 UTC by agoose77

This PR adds some basic styling for mdast nodes emitted by https://github.com/executablebooks/sphinx-ext-mystmd

2024-07-22 20:40 UTC, rowanc1 requested changes
As these are specific for sphinx, are not used in scientific , and the AST might change. I think these should be their own package. Ideally we have them as an export out of `myst-ext-autodoc/react`?

Doing that makes it a bit harder to do the auto reload, but I think it is maybe worth it?

If we did that, then I still think these should come in by default in the themes we have, but other themes can make different choices.

2024-07-22 20:40 UTC, rowanc1 commented on packages/myst-to-react/src/autodoc.tsx
> +    >
```suggestion
    <span className="whitespace-pre">
```

2024-07-22 20:40 UTC, rowanc1 commented on packages/myst-to-react/src/autodoc.tsx
> +      >
```suggestion
      <span className="whitespace-pre font-bold">
```

2024-07-22 20:40 UTC, rowanc1 commented on packages/myst-to-react/src/autodoc.tsx
> +      >
```suggestion
      <dt className="font-mono font-light">
```

2024-07-22 20:40 UTC, rowanc1 commented on packages/myst-to-react/src/autodoc.tsx
> +        <span>&#x2192; </span>
As this is decoration, probably better in css? You can do this in a `:before` node and set the content to an arrow.

2024-07-30 15:00 UTC, rowanc1 commented
In conversation today: we should see how far we can get on doing a pre-transform on the AST to use `kind` to differentiate, e.g., a field list, on a `definitionList`.

2024-08-01 13:26 UTC, agoose77 commented
Closed in favour of #443

2024-08-01 13:26 UTC, closed without merging